var sampleItems = [
  { name: "Arugula, astro", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Basil tips", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Beets, baby - bulk or bunch", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Beets, Bulk (red, chioggia, golden)", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Bok Choy", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Broccoli", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Brussel Sprouts", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Cabbage, green and red", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Cabbage, Napa", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Carrots, baby", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Carrots, bulk", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Cauliflower", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Chamomile", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Chard (red, green, rainbow) - bulk or bunch", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Cilantro", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Cucumbers - slicing, pickling & English", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Dill", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Eggplant", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Endive", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Fennel", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Kale (Lacinato, green and red) - bulk, bunch or stripped", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Kohlrabi", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Leeks", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Lettuce Mix", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Lettuce, Romaine  ", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Lettuce, Head - green", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Lettuce, Head - red", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Lettuce, Head - Butter", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Mizuna", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Onions, Yellow and Sweet", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Onions, Red", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Onions, green - bunch", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Parsley", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Peppers, Anaheim", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Peppers, Bell", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Peppers, Jalapeno", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Potatoes, German Butterball", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Potatoes, Fingerling", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Potatoes, New", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Potatoes, Specialty (Purple Viking, All Blue)", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Potatoes, Red Norland", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Pumpkin", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Radish, Daikon", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Scallions - bunch", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Shallots", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Spinach, Braising", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Spinach, Baby", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Squash, summer, mixed", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Squash, winter, mixed", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Tomatoes, cherry", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Tomatoes, heirloom", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' },
  { name: "Tomatoes, slicing", date: ' ', units: 'lbs', quantity: 5, anotherField: 'thing' }
]

module.exports = sampleItems
